### ISSUE TITLE
Compilation error: call to 'HTTPClient::begin' 

### ISSUE THREAD

**Issue by bixpii** [davidegironi/espduckdns#2]
Hi.
I get this issues. Can you fix it?

`/Users/bixpii/Downloads/espduckdns-master/firmware/ESPDuckDNS/ESPDuckDNS.ino: In function 'int ddnsUpdate()':
/Users/bixpii/Downloads/espduckdns-master/firmware/ESPDuckDNS/ESPDuckDNS.ino:415:15: error: call to 'HTTPClient::begin' declared with attribute error: obsolete API, use ::begin(WiFiClient, url)
  415 |     http.begin(getrequest);
      |     ~~~~~~~~~~^~~~~~~~~~~~
Multiple libraries were found for "Ticker.h"
  Used: /Users/bixpii/Library/Arduino15/packages/esp8266/hardware/esp8266/3.0.2/libraries/Ticker
  Not used: /Users/bixpii/Documents/Arduino/libraries/Ticker
exit status 1

Compilation error: call to 'HTTPClient::begin' declared with attribute error: obsolete API, use ::begin(WiFiClient, url)`

**Comment by davidegironi** [comment]
You should use an older version of Arduino compiler or port it to the new HTTP library, cause HTTPClient::begin it's been deprecated.
